"# Python Script to Add Two Numbers"  
"def add_numbers(num1, num2):"  
"    return num1 + num2"  
"def main():"  
"    number1 = float(input('Enter the first number: '))"  
"    number2 = float(input('Enter the second number: '))"  
"    result = add_numbers(number1, number2)"  
"    print(f'The sum of {number1} and {number2} is {result}')"  
"if __name__ == '__main__':"  
"    main()" 
